### ISSUE TITLE
Error when trying to setup Node.js

### ISSUE THREAD

**Issue by nicko996** [BlocTheWorker/Inworld-Skyrim-Mod#1]
Following the instructions at step 4 of Typescript Node.js Project section
when I execute npm start command I get the following message:

npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\nicko\AppData\Local\npm-cache\_logs\2023-05-01T21_07_10_117Z-debug-0.log

**Comment by nicko996** [comment]
I updated the `package.json` to the following and it fixed it:
```json
{
  "name": "client",
  "main": "index.js",
  "scripts": {
    "start": "ts-node SkyrimClient.ts"
  },
  "dependencies": {
    "ts-node": "^10.8.2",
    "@fastify/websocket": "^7.1.2",
    "@inworld/nodejs-sdk": "^1.1.6",
    "axios": "^1.3.2",
    "dotenv": "^16.0.3",
    "fastify": "^4.12.0"
    }
}
```  
<del>Now i'm getting a "Token expired or doesnt exist. Access Token: undefined, Current Expiration Date: undefined" message, but I guess that's my problem</del>  
nevermind, read now the code, it is the correct behaviour the first time it is called

**Comment by BlocTheWorker** [comment]
Some parts of that document were generated by AI, and I forgot to proofread them. Notes taken for the future :) 
I will update the package.json file as soon as possible
