### ISSUE TITLE
SKSE build

### ISSUE THREAD

**Issue by dadofdragonschannel** [BlocTheWorker/Inworld-Skyrim-Mod#6]
Hi! I had tried to build SKSE, but it has ended with error. Maybe I can contact with you somehow?

-- Configuring done (0.1s)
CMake Error at CMakeLists.txt:14 (add_library):
  Cannot find source file:

    SOURCES

-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by BlocTheWorker** [comment]
Please follow [SkyrimScripting's great template](https://github.com/SkyrimScripting/SKSE_Template_HelloWorld) first. Make sure you installed vcpkg properly and your Visual Studio is fetching the packages in there without any problem.
